name: Generate and upload PDF

on:
  push:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
    
    # install dependencies
    - run: yarn

    # build the pdf
    - run: yarn pdf

    # move pdf to correct output file name
    - run: mv 'The Eth2 Book.pdf' book.pdf

    # upload pdf to ipfs
    - uses: aquiladev/ipfs-action@v0.2.1-alpha.4
      with:
        path: './book.pdf'        
